- name: play level variables
  hosts: local
  connections: local 
  vars:
     COURSE: ansible
     DURATION: 10hrs
  tasks:
   - name: print the course info
     ansible.builtin.debug:
       msg: "course name is :{{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"
    