- name: conditions
  hosts: local
  connection: local
  vars:
    number: 5
  task: 
  - name: check number is less then 10 or not
    ansible.builtin.debug:
    msg: "Given number {{ number }} is less then 10"
  when: number < 10