- name: Install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print names
    ansibe.builtin.package:
      name: "{{ item }}"
      state: latest
    loops:
    - nginx
    - mysql
    - zip