- nmae: install packages
  hosts: local
  connection: local
  task:
  - name: print names
    ansibe.builtin.package:
      name: "{{ item }}"
      state: latest
    loops:
    - nginx
    - mysql
    - zip